services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
    command: sh -c "php artisan serve --host=0.0.0.0"
    networks:
      - meet-and-music-network

  node:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - meet-and-music-network

networks:
  meet-and-music-network:
    driver: bridge 